# Generated by Django 5.0.7 on 2024-08-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='price',
            field=models.FloatField(),
        ),
    ]
