# Generated by Django 5.0.7 on 2024-08-12 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0002_alter_itemmodel_price'),
        ('login', '0002_alter_usermodel_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.itemmodel')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.usermodel')),
            ],
        ),
    ]
