# Generated by Django 5.0.7 on 2024-08-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
