# Generated by Django 5.0.7 on 2024-08-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_usermodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userName',
            field=models.CharField(max_length=80),
        ),
    ]
