# Generated by Django 5.0.7 on 2024-08-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_usermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userName',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
